@dotnetAPI = http://localhost:5167

GET {{dotnetAPI}}/okCode/
Headers:
X-API-Key: "tu llave API aquí"
Accept: application/json

### Get Users
GET {{dotnetAPI}}/getUsers/
Headers:
X-API-Key: "tu llave API aquí"
Accept: application/json

### Create User
POST {{dotnetAPI}}/createUser/
Headers:
X-API-Key: "tu llave API aquí"
Content-Type: application/json

{
    "name": "Amin Espinoza",
    "username": "aminespinoza",
    "password": "M3_s5p2r_p1ssw4rd"
}